version: '3.8'

services:

  db:
    container_name: db
    image: postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/

  backend:
    build:
      context: .
    env_file:
      - ./.env
    container_name: backend
    command: gunicorn config.wsgi:application --workers 2 --threads 1 --timeout 60 --preload --bind 0.0.0.0:8000
    ports:
      - '8000:8000'
    restart: always
    depends_on:
      - db
      - redis
    volumes:
      - static:/app/back_static
      - media:/app/back_media


  celery:
    build:
      context: .
    env_file:
      - ./.env
    command: celery -A config worker --loglevel=info
    depends_on:
      - backend
      - redis

  redis:
    image: redis:latest
    env_file:
      - ./.env
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis_password

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/app/back_static
      - media:/app/back_media


volumes:
  static:
  media:
  db_data: