# Generated by Django 5.2.4 on 2025-07-14 11:21

import common.utils
import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFooter',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Ссылка на соцсеть')),
                ('image', models.ImageField(help_text='Загрузите изображение соцсети', max_length=1000, upload_to=common.utils.setup_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'svg'])], verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'контакты (footer)',
                'verbose_name_plural': 'контакты (footer)',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('title', models.CharField(max_length=30, verbose_name='Название дисциплины')),
            ],
            options={
                'verbose_name': 'дисциплина',
                'verbose_name_plural': 'дисциплина',
            },
        ),
        migrations.CreateModel(
            name='EmailPhoneFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('email', models.CharField(max_length=50, verbose_name='Почта поддержки в Footer')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер в Footer')),
            ],
            options={
                'verbose_name': 'почта,номер (footer)',
                'verbose_name_plural': 'почта,почта,номер (footer)',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('title', models.CharField(help_text='Заголовок для блока "Аккредитация для СМИ" (можно поменять)', max_length=50, verbose_name='Заголовок')),
                ('date', models.CharField(help_text='Дата (до 22 октября 18:00)', max_length=50, verbose_name='Дата')),
                ('email', models.CharField(help_text='Почта (info@streetrussia.ru)', max_length=50, verbose_name='Почта')),
                ('fio', models.CharField(help_text='Имя - фамилия (Елизавета Сырыгина)', max_length=65, verbose_name='Имя - фамилия')),
            ],
            options={
                'verbose_name': 'блок Аккредитация для СМИ',
                'verbose_name_plural': 'блок Аккредитация для СМИ',
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('text', models.TextField(help_text='Описание блока УЛИЦЫ', verbose_name='Текстовое описание')),
            ],
            options={
                'verbose_name': 'блок улицы',
                'verbose_name_plural': 'блок улицы',
            },
        ),
    ]
