# Generated by Django 5.2.4 on 2025-07-26 14:57

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='info',
        ),
        migrations.CreateModel(
            name='ProgramDate',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='tours.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'дата программы',
                'verbose_name_plural': 'дата программы',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('moderator', models.ManyToManyField(blank=True, null=True, related_name='programs', to='tours.moderator')),
                ('program_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='tours.programdate', verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'программа',
                'verbose_name_plural': 'программа',
            },
        ),
        migrations.DeleteModel(
            name='Leader',
        ),
        migrations.AddConstraint(
            model_name='programdate',
            constraint=models.UniqueConstraint(fields=('date', 'tour'), name='unique_program_date_per_tour'),
        ),
    ]
